Update PaigeBranch

diff --git a/PaigeBranch b/PaigeBranch
--- a/PaigeBranch
+++ b/PaigeBranch
@@ -18,45 +18,12 @@ then
     exit 2
 fi
 
-if [[ ${wholecard[$i]} = *[^0-9\]* ]]  #checking if the file has any non-digit characters
-   then
-       echo "seed line format error"
-       exit 3
-   fi
-
-
-for i in {0..30}
-do
-    if [[ $i == 0 ]]    #checking for layout errors
-    then
-        if [[ ${wholecard[$i]} = *[0-9]* ]]   #checking if the first row contains any non-digit characters
-        then
-            echo "card format error (layout error)"
-            exit 3
-        fi
-    else        #checking if the formatting of the matrix is wrong
-        if [[ $(echo ${wholecard[$i]} | grep "^[0-9]\+ [0-9]\+ [0-9]\+ [0-9]\+$") == "" ]]
-        then
-            echo "card format error (matrix format error)"
-            exit 3
-        fi
-    fi
-done
 
 
 
 
-#exit status 3
-
-if [[ ${wholecard[$i]} = *[^0-9\]* ]]  #checking if the file has any non-digit characters
-   then
-       echo "seed line format error"
-       exit 3
-   fi
-
-for i in {0..30}
-do
-
+#can use grep maybe for finding non number characters
+#exit 3 - see if seed line has white space, extra numbers, etc
 
 declare -a wholecard=()
 while read line;
@@ -75,23 +42,59 @@ fi
 echo "here is the element at the first index ${wholecard[1]}"
 
 
+#exit status 3
+
+if [[ ! "${wholecard[0]}" =~ [0-9][0-9][0-9][0-9] ]]  #checking if the file has any non-digit characters
+then
+    echo "seed line format error"
+    exit 3
+fi
+
+for i in {1..26}
+do
+    if [[ ! "${wholecard[$i]}" =~ [0-9][0-9] ]]
+    then
+        echo "card format error (layout error)"
+        exit 3
+    fi
+done
+
+
+
+
+
 seed=${wholecard[0]}
 
-row1=( "${wholecard[@]:1:5}" )
+rowone=( ${wholecard[@]:1:5} )
 
-row2=( "${wholecard[@]:6:5}" )
+rowtwo=( ${wholecard[@]:6:5} )
 
-row3=( "${wholecard[@]:11:5}" )
+rowthree=( ${wholecard[@]:11:2} "00m "${wholecard[@]:14:2} )
 
-row4=( "${wholecard[@]:16:5}" )
+rowfour=( ${wholecard[@]:16:5} )
 
-row5=( "${wholecard[@]:21:5}" )
+rowfive=( ${wholecard[@]:21:5} )
 
-echo "${row1[@]}"
-echo "${row2[@]}"
-echo "${row3[@]}"
-echo "${row4[@]}"
-echo "${row5[@]}"
+#Need to add extra spaces inbetween the elements in each rowarray. 
+#This will also instantiate our variables for display
+
+row1=()
+row2=()
+row3=()
+row4=()
+row5=()
+
+
+
+
+for i in {0..4}
+do
+    row1+=("${rowone[$i]} ")
+    row2+=("${rowtwo[$i]} ")
+    row3+=("${rowthree[$i]} ")
+    row4+=("${rowfour[$i]} ")
+    row5+=("${rowfive[$i]} ")
+done
 
 
 
@@ -99,6 +102,78 @@ echo "${row5[@]}"
 #then adds randomly generated numbers to it
 #then checks if random number was previously generated
 #if so generates a new one
+
+declare -a calledNums=()
+declare -a calllist=()
+ran=`expr $RANDOM \% 75 + 1`
+
+wholecardnoseed=${wholecard[@]:1}
+
+
+
+while true
+do
+    clear
+    #the code under here will display the card and modify it with the marks.  
+    echo "CALL LIST: ${calllist[@]}"
+    echo " L   I   N   U   X"
+    echo "${row1[@]}"
+    echo "${row2[@]}"
+    echo "${row3[@]}"
+    echo "${row4[@]}"
+    echo "${row5[@]}"  
+    
+    
+    read -r -n1 -p "enter any key to get a call or q to quit: " input
+    if [[ "$input" =~ [q] ]]
+    then
+        exit 0
+    else
+        echo "random num is: $ran"
+        #This is adding elements to the called numbers list 
+        if [ ${#calledNums[@]} -eq 0 ] || [[ ! "${calledNums[*]}" =~ "$ran" ]]
+        then
+            calledNums+=($ran)
+            #This is checking $ran and adding L/I/N/U/X
+            if [ $ran -le 15 ] && [ $ran -ge 1 ]
+            then
+                calllist+=("L""$ran")
+            elif [ $ran -le 30 ] && [ $ran -ge 16 ]
+            then
+                calllist+=("I""$ran")
+            elif [ $ran -le 45 ] && [ $ran -ge 31 ]
+            then
+                calllist+=("N""$ran")
+            elif [ $ran -le 60 ] && [ $ran -ge 46 ]
+            then
+                calllist+=("U""$ran")
+            elif [ $ran -le 75 ] && [ $ran -ge 61 ]
+            then
+                calllist+=("X""$ran")
+            fi
+        fi
+        #This is checking if $ran is in the card
+        if [[ "${wholecardnoseed[*]}" =~ "$ran" ]]
+        then
+            echo "$ran is in the card"
+            #checks card if ran is in it, then checks rows/cols/corners and
+            #adds m to the row. 
+            #will need a final check to go through rows/cols/corners and use
+            #counter tmp or i/j to see if rows/cols contains 5 m's or if 
+            #corners has 4 m's 
+        fi
+
+    fi
+    #generates new random number
+    ran=`expr $RANDOM \% 75 + 1`
+done
+
+
+#first checks if the calledNums array is empty
+#then adds randomly generated numbers to it
+#then checks if random number was previously generated
+#if so generates a new one
+
 declare -a calledNums=()
 ran=`expr $RANDOM \% 75 + 1`
 
@@ -112,12 +187,12 @@ if [[ "$ran" =~ "${calledNums[*]}" ]]
         ran=`expr $RANDOM \% 75 + 1`
 fi
 
+
+
 #marks the card if generated number is in the card
 #similar to Dan's code with slight changes
 
 
-
-#read -sp 'Hit any button to draw a number and hit q to quit."
 
 
 for i in $wholecard
@@ -141,16 +216,16 @@ do
 done
 
 #these will be the error checks, the first one here is checking if there are 26 items in the array.
+
 if [ ${#wholecard[@]} == 26 ]
 then
     echo "the length is 26 items"
 fi
 
 
-
 #exit code 4 - card format error
 
-#1stcolumn=${wholecard[@]}
+
 
 firstcolumn=( ${wholecard[1]} ${wholecard[6]} ${wholecard[11]} ${wholecard[16]} ${wholecard[21]} )
 
@@ -209,5 +284,54 @@ do
     then
        echo "card format error"
        exit 4
+    fi
+done
+
+
+#exit status 4 - part two
+#checks if LINUX card contains duplicate values, if so prints error and exits game
+
+for i in "${firstcolumn[@]}"
+do
+    if [[ "${firstcolumn[*]}" =~ "${firstcolumn[$i]}" ]]
+    then
+        echo "card format error (has duplicates)"
+        exit 4
+    fi
+done
+
+for i in "${secondcolumn[@]}"
+do
+    if [[ "${secondcolumn[*]}" =~ "${secondcolumn[$i]}" ]]
+    then
+        echo "card format error (has duplicates)"
+        exit 4
+    fi
+done
+
+for i in "${thirdcolumn[@]}"
+do
+    if [[ "${thirdcolumn[*]}" =~ "${secondcolumn[$i]}" ]]
+    then
+        echo "card format error (has duplicates)"
+        exit 4
+    fi
+done
+
+for i in "${fourthcolumn[@]}"
+do
+    if [[ "${fourthcolumn[*]}" =~ "${fourthcolumn[$i]}" ]]
+    then
+        echo "card format error (has duplicates)"
+        exit 4
+    fi
+done
+
+for i in "${fifthcolumn[@]}"
+do
+    if [[ "${fifthcolumn[*]}" =~ "${fifthcolumn[$i]}" ]]
+    then
+        echo "card format error (has duplicates)"
+        exit 4
     fi
 done
