Update PaigeBranch

diff --git a/PaigeBranch b/PaigeBranch
--- a/PaigeBranch
+++ b/PaigeBranch
@@ -1,5 +1,63 @@
 #!/bin/bash
 
+#exit status 1
+
+if [ ! -f $1 -o ! -r $1 ]
+then
+    echo "Input file is missing or unreadable."
+    exit 1
+fi
+
+
+
+#exit status 2
+
+if [[ $(cat $1 | wc -l) != 6 ]]
+then
+    echo "input file does not have 6 lines"
+    exit 2
+fi
+
+if [[ ${wholecard[$i]} = *[^0-9\]* ]]  #checking if the file has any non-digit characters
+   then
+       echo "seed line format error"
+       exit 3
+   fi
+
+
+for i in {0..30}
+do
+    if [[ $i == 0 ]]    #checking for layout errors
+    then
+        if [[ ${wholecard[$i]} = *[0-9]* ]]   #checking if the first row contains any non-digit characters
+        then
+            echo "card format error (layout error)"
+            exit 3
+        fi
+    else        #checking if the formatting of the matrix is wrong
+        if [[ $(echo ${wholecard[$i]} | grep "^[0-9]\+ [0-9]\+ [0-9]\+ [0-9]\+$") == "" ]]
+        then
+            echo "card format error (matrix format error)"
+            exit 3
+        fi
+    fi
+done
+
+
+
+
+#exit status 3
+
+if [[ ${wholecard[$i]} = *[^0-9\]* ]]  #checking if the file has any non-digit characters
+   then
+       echo "seed line format error"
+       exit 3
+   fi
+
+for i in {0..30}
+do
+
+
 declare -a wholecard=()
 while read line;
 do
